spring:
  jpa:
    properties.hibernate:
      jdbc.batch_size: 50
      default_batch_fetch_size: 50
    show-sql: true
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2.console.enabled: true
  flyway:
    enabled: true
    user: sa
    password: password
    schemas: testdb
    url: jdbc:h2:mem:testdb
    locations: filesystem:db/migration

